export const SELECT_HOST = 'SELECT_HOST';
export const INVOKE_ASSESSMENT = 'INVOKE_ASSESSMENT';
export const RETRIEVE_ASSESSMENT = 'RETRIEVE_ASSESSMENT';
export const RETRIEVE_OPTIONS = 'RETRIEVE_OPTIONS';
export const RETRIEVE_RESULTS = 'RETRIEVE_RESULTS';
export const UPDATE_OPTIONS = 'UPDATE_OPTIONS';
export const ADD_COUNT = 'ADD_COUNT';