const actionTypes = {
	SELECT_HOST : 'SELECT_HOST',
	INVOKE_ASSESSMENT : 'INVOKE_ASSESSMENT',
	RETRIEVE_ASSESSMENT : 'RETRIEVE_ASSESSMENT',
	RETRIEVE_OPTIONS : 'RETRIEVE_OPTIONS',
	RETRIEVE_RESULTS : 'RETRIEVE_RESULTS',
	UPDATE_OPTIONS : 'UPDATE_OPTIONS'
};

export default actionTypes;