const actionTypes = {
	POPUP_OPEN : 'POPUP_OPEN',
	UPDATE_HOST: 'UPDATE_HOST',
	INVOKE_ASSESSMENT : 'INVOKE_ASSESSMENT',
	RETRIEVE_ASSESSMENT : 'RETRIEVE_ASSESSMENT',
	RETRIEVE_OPTIONS : 'RETRIEVE_OPTIONS',
	RETRIEVE_RESULTS : 'RETRIEVE_RESULTS',
	UPDATE_OPTIONS : 'UPDATE_OPTIONS',
	HOST_CHANGE: 'HOST_CHANGE'
};

export default actionTypes;